[workspace]
members = ["serde_arrow", "bench", "example", "integration_tests"]
default-members = ["serde_arrow"]

resolver = "2"

[profile.bench]
debug = 'line-tables-only'
codegen-units = 1
lto = "fat"
