[project]
description = "The dependencies required to run the integration tests"
name = "serde-arrow"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
    "pyarrow~=22.0",
    "matplotlib~=3.10.8",
    "numpy~=2.3",
    "ruff~=0.14.6",
    "polars~=1.35",
]

[tool.uv]
package = false
