[package]
name = "arrow2-to-arrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "35", features = ["ffi"] }
arrow2 = "0.17"
